apiVersion: v2
name: secrets
version: 0.0.1
appVersion: 0.0.1
description: vault, secrets-store-csi-driver, external-secrets
dependencies:
- name: "vault"
  version: "0.25.0"
  condition: vault.enabled
  repository: "https://helm.releases.hashicorp.com"
- name: "secrets-store-csi-driver"
  version: "1.3.4"
  condition: secrets-store-csi-driver.enabled
  repository: "https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts"
- name: "external-secrets"
  version: "0.9.5"
  condition: external-secrets.enabled
  repository: "https://charts.external-secrets.io"