vault:
  enabled: true
  injector:
    enabled: false
  csi:
    # installs secrets-store-csi-driver-provider-vault
    enabled: true

secrets-store-csi-driver:
  enabled: true

external-secrets:
  enabled: true