apiVersion: v2
name: ingress
version: 0.0.5
appVersion: 0.0.1
description: ingress, tls
dependencies:
- name: "ingress-nginx"
  version: "4.8.0"
  condition: ingress-nginx.enabled
  repository: "https://kubernetes.github.io/ingress-nginx"
- name: "cert-manager"
  version: "1.13.1"
  condition: cert-manager.enabled
  repository: "https://charts.jetstack.io"