prometheus:
  enabled: true

prometheus-adapter:
  enabled: true

loki-distributed:
  enabled: true

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://observability-loki-distributed-gateway.observability.svc.cluster.local:3100/loki/api/v1/push

grafana:
  enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://observability-prometheus-server.observability.svc.cluster.local/
        - name: Loki
          type: loki
          url: http://observability-loki-distributed-gateway.observability.svc.cluster.local/

  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "grafana-dashboard-overview"